default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['TPI-RUBY_DATABASE_USERNAME'] %>
  password: <%= ENV['TPI-RUBY_DATABASE_PASSWORD'] %>
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: TPI-Ruby_development


test:
  <<: *default
  database: TPI-Ruby_test


production:
  <<: *default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['TPI-RUBY_DATABASE_USERNAME'] %>
  password: <%= ENV['TPI-RUBY_DATABASE_PASSWORD'] %>
